bulker:
  volumes: ['/ext', '/tmp', '$HOME', '/project']
  envvars: ['GENOMES', 'DISPLAY', 'TEXINPUTS', 'CARAVEL', 'CODE', 'PROCESSED', 'SRABAM', 'SRARAW', 'DATA']
  default_crate_folder: ${HOME}/bulker_crates
  container_engine: docker
  singularity_image_folder: ${HOME}/simages
  executable_template: /home/nsheff/.local/lib/python3.7/site-packages/bulker/templates/docker_executable.jinja2
  crates:
    base: ${HOME}/bulker_crates/base
    peppro: /home/nsheff/bulker_crates/peppro
    demo: /home/nsheff/bulker_crates/demo
    nsheff: /home/nsheff/bulker_crates/nsheff
    pi: /home/nsheff/bulker_crates/pi
    databio: /home/nsheff/bulker_crates/databio
    demo2: /home/nsheff/bulker_crates/demo2
  build_template: /home/nsheff/.local/lib/python3.7/site-packages/bulker/templates/docker_build.jinja2
