bulker:
  volumes: ['/ext', '/tmp', '$HOME', '/project']
  envvars: ['GENOMES', 'DISPLAY', 'TEXINPUTS']
  default_crate_folder: ${HOME}/bulker_crates
  singularity_image_folder: ${HOME}/simages
  executable_template: singularity_executable.jinja2
  crates:
    base: ${HOME}/bulker_crates/base
    peppro: /home/nsheff/bulker_crates/peppro
    demo: /home/nsheff/bulker_crates/demo
    nsheff: /home/nsheff/bulker_crates/nsheff
