bulker:
  volumes: ['/ext', '/tmp', '$HOME', '/project']
  envvars: ['GENOMES', 'DISPLAY', 'TEXINPUTS']
  default_crate_folder: ${HOME}/bulker_crates
  singularity_image_folder: ${HOME}/simages
  container_system: docker
  executable_template: null
  build_template: null
  crates:
    base: ${HOME}/bulker_crates/base
    peppro: /home/nsheff/bulker_crates/peppro
    demo: /home/nsheff/bulker_crates/demo
    nsheff: /home/nsheff/bulker_crates/nsheff
