# Dockerfile for refgenie environment:

FROM ubuntu:16.04

MAINTAINER Nathan Sheffield <nathan@code.databio.org>
RUN apt-get update && apt-get install -y wget git unzip
RUN apt-get install -y python python-pip
RUN apt-get install -y curl

RUN wget -O ~/bowtie.zip "https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.0/bowtie2-2.3.0-linux-x86_64.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fbowtie-bio%2Ffiles%2Fbowtie2%2F2.3.0%2F&ts=1485465820&use_mirror=kent"


RUN unzip ~/bowtie.zip

# bowtie2 dependencies
RUN apt-get install -y libtbb-dev


# install samtools

# samtools dependencies:
RUN apt-get install -y libz-dev libncurses-dev

RUN wget -O ~/samtools.bz2 https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
RUN tar -xf ~/samtools.bz2
RUN ls
RUN cd /samtools-1.3.1 && make

ENV PATH="/samtools-1.3.1:/bowtie2-2.3.0:${PATH}"

RUN git clone https://github.com/databio/refgenie.git

RUN pip install --user https://github.com/epigen/pypiper/zipball/master
RUN pip install --user pyyaml

# For future reference, if I need to add a PPA, here's how to do it:
#RUN apt-get install -y software-properties-common  python-software-properties && apt-add-repository ppa:brightbox/ruby-ng
#RUN apt-get update 
