# Dockerfile for mediabuilder:

FROM ubuntu:16.04

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

# Updating is required before any apt-gets
# Install prerecs and latex
RUN apt-get update && apt-get install -y wget git
RUN apt-get install -y python3
RUN apt-get install -y make
RUN apt-get install -y texlive-latex-recommended
RUN apt-get install -y texlive-latex-extra 


RUN apt install -y librsvg2-bin
RUN apt-get install -y context
# Install pandoc

#RUN wget https://github.com/jgm/pandoc/releases/download/1.16.0.2/pandoc-1.16.0.2-1-amd64.deb
#RUN dpkg -i pandoc-1.16.0.2-1-amd64.deb

#RUN wget https://github.com/jgm/pandoc/releases/download/2.0/pandoc-2.0-3-amd64.deb
#RUN dpkg -i pandoc-2.0-3-amd64.deb

#RUN wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
#RUN dpkg -i pandoc-1.19.2.1-1-amd64.deb

RUN wget https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb
RUN dpkg -i pandoc-2.1.3-1-amd64.deb