# Dockerfile for my R DEVELOPMENT environment:

# I originally used as base my own R docker image, but then I found Dirk's
# excellent Rocker project, and the bioconductor images based on these, and it
# makes more sense for me to just use these instead...

# Switch to using the bioconductor maintained docker images
# FROM sheffien/rim
# FROM rocker/r-devel
FROM bioconductor/devel_core2
MAINTAINER Nathan Sheffield <nathan@code.databio.org>

################################################################################
# Some of these dependencies will be already installed by the parent images;
# But just to make sure, run these installs here:

# Updating is required before any apt-gets
RUN sudo apt-get update && apt-get install -y --force-yes\
  # Required for R Package XML
  libxml2-dev \
  # Curl; required for RCurl; but present in upstream images
  # libcurl4-gnutls-dev \
  # GNU Scientific Library; required by MotIV
  libgsl0-dev \
  # Open SSL is used, for example, devtools dependency git2r
  libssl-dev \
   # CMD Check requires to check pdf size
  qpdf

# Boost libraries are helpful for some r packages
RUN sudo apt-get update && apt-get install -y --force-yes \
libboost-all-dev

################################################################################
# I put these COPY statements in separately, so that the whole thing
# isn't invalidated (causing unnecessary cache rebuilds)
# with an unrelated change in Rsetup/
# If you COPY a whole folder, it busts the cache if anything in that folder
# changes, so it's better to add each file separately if the folder may change

#COPY Rprofile .Rprofile

# I put these COPY statements in separately, so that the whole thing
# isn't invalidated (causing unnecessary cache rebuilds)
# with an unrelated change in Rsetup/

COPY Rsetup/install_fonts.R Rsetup/install_fonts.R
COPY Rsetup/fonts Rsetup/fonts
RUN Rscript Rsetup/install_fonts.R

# Install packages
COPY Rsetup/Rsetup.R Rsetup/Rsetup.R
RUN Rscript Rsetup/Rsetup.R

COPY Rsetup/rpack_basic.txt Rsetup/rpack_basic.txt
RUN Rscript Rsetup/Rsetup.R --packages=Rsetup/rpack_basic.txt

COPY Rsetup/rpack_basic.txt Rsetup/rpack_shiny.txt
RUN Rscript Rsetup/Rsetup.R --packages=Rsetup/rpack_shiny.txt

# If you want to develop R packages on this machine (need biocCheck):
COPY Rsetup/rpack_biodev.txt Rsetup/rpack_biodev.txt
RUN Rscript Rsetup/Rsetup.R --packages=Rsetup/rpack_biodev.txt
# Add BiocCheck executable to PATH
ENV PATH /usr/local/lib/R/site-library/BiocCheck/script/:${PATH}
RUN chmod 777 /usr/local/lib/R/site-library/BiocCheck/script/BiocCheck

# CMD Check requires to check pdf size
RUN sudo apt-get install -y --force-yes qpdf


# I think it's good to have this one last, so if you change anything in the bin,
# it won't make you reinstall all the packages.


# Copy over the stuff in Rpack and add it to path
COPY Rpack/ Rpack/
ENV PATH /Rpack:${PATH}

# Bioconductor packages may not be up-to-date. This updates them.
RUN Rscript -e 'source("https://bioconductor.org/biocLite.R");biocLite(ask=FALSE)'

RUN sudo apt-get update && apt-get install -y --force-yes\
  libsodium-dev