FROM nsheff/python3

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

RUN pip3 install mkdocs
RUN pip3 install lucidoc
RUN pip3 install --upgrade https://github.com/databio/mkdocs-databio/zipball/master
