# Dockerfile for liquid template populating

FROM ruby

MAINTAINER Nathan Sheffield <nathan@code.databio.org>
RUN gem install liquid
COPY includes/liquify.rb liquify.rb

ENTRYPOINT ["ruby", "/liquify.rb"]

