FROM ubuntu:18.04

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

# Updating is required before any apt-gets
RUN apt-get update && apt-get install -y wget git
RUN apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

CMD ["python3"]
