# Dockerfile for my R DEVELOPMENT environment:

# I originally used as base my own R docker image, but then I found Dirk's
# excellent Rocker project, and the bioconductor images based on these, and it
# makes more sense for me to just use these instead...

# FROM sheffien/rim
# Switch to using the bioconductor maintained docker images
# FROM bioconductor/devel_core

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

# Updating is required before any apt-gets
RUN sudo apt-get update

# This is a huge (250 MB) package but R CMD check
# requires it so I have to stick it in my dev container.
RUN sudo apt-get install -y --force-yes texlive-latex-base

# CMD Check requires pandoc to check README
RUN sudo apt-get install -y --force-yes pandoc

ADD Rsetup/Rdev.R Rsetup/Rdev.R
RUN Rscript Rsetup/Rdev.R

# I put these COPY statements in separately, so that the whole thing
# isn't invalidated (causing unnecessary cache rebuilds) 
# with an unrelated change in Rsetup/

# If you want to develop R packages on this machine (need biocCheck):
RUN Rscript Rsetup/Rsetup.R --packages=Rsetup/rpack_biodev.txt

COPY Rpack/ bin/

# CMD Check requires to check pdf size
RUN sudo apt-get install -y --force-yes qpdf

# CMD Check requires to check pdf size
# texinfo has texi2dvi, used for creating pdf versions.
RUN sudo apt-get install -y --force-yes texinfo
# sudo apt-get install texinfo

#url.sty not found
RUN sudo apt-get install -y --force-yes texlive-latex-recommended desktop-file-utils
# sudo apt-get install texlive-fonts-recommended

