FROM nsheff/tex

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

ENV DEBIAN_FRONTEND=noninteractive

# Updating is required before any apt-gets
RUN apt-get install -y texlive-latex-recommended
RUN apt-get install -y texlive-latex-extra 
RUN apt-get install -y texlive-science
RUN apt-get install -y texlive-xetex
RUN apt-get install -y texlive-bibtex-extra biber
RUN apt-get install -y context
RUN apt-get install -y texlive-fonts-extra
