FROM ubuntu:18.04
MAINTAINER Nathan Sheffield <nathan@code.databio.org>
RUN apt-get update && apt-get install -y cmake zlib1g-dev libboost-system-dev libboost-program-options-dev libpthread-stubs0-dev libfuse-dev libudev-dev git build-essential
RUN mkdir console-client
RUN git clone https://github.com/pcloudcom/console-client.git console-client
RUN cd console-client/pCloudCC/lib/pclsync/ && make clean && make fs
RUN cd console-client/pCloudCC/lib/mbedtls/ && cmake . && make clean && make
RUN cd console-client/pCloudCC/ && cmake . && make && make install
RUN ldconfig
RUN apt-get install fuse
