FROM nsheff/python3

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

RUN wget http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.4/sratoolkit.2.10.4-ubuntu64.tar.gz -O /tmp/sratoolkit.tar.gz \
	&& tar zxvf /tmp/sratoolkit.tar.gz -C /opt/ && rm /tmp/sratoolkit.tar.gz

ENV PATH="/opt/sratoolkit.2.10.4-ubuntu64/bin/:${PATH}"

# Updating is required before any apt-gets
RUN pip install geofetch
