FROM ubuntu:latest
MAINTAINER Nathan Sheffield <nathan@code.databio.org>

################################################################################
# Some of these dependencies will be already installed by the parent images;
# But just to make sure, run these installs here:

# Updating is required before any apt-gets
RUN apt-get update && apt-get install -y\
	wget \
	xdg-utils \
	evince

################################################################################

RUN wget https://github.com/JabRef/jabref/releases/download/v5.0/JabRef-5.0-portable_linux.tar.gz

# 4.2, 4.3, and 4.3.1 have bugs that break it. It looks like 4.4 will work.


#ADD  "JabRef-4.1-dev--snapshot--2017-12-22--master--d9644d018.jar" JabRef.jar

RUN tar -xf JabRef-5.0-portable_linux.tar.gz
RUN apt-get update && apt-get install -y xdg-utils --fix-missing
ENV PATH /JabRef/bin

