# Dockerfile for Jekyll environment:
# Build me with: 
# Run me with: docker run -p 4000:4000 -it -v ~/web:/web sheffien/jim  bash

FROM ubuntu

MAINTAINER Nathan Sheffield <nathan@code.databio.org>
RUN apt-get update && apt-get install -y wget ffmpeg

ENTRYPOINT ["ffmpeg"]

