FROM nsheff/python3

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

# can take this out when upgrade 2.10.4 works
# it's broken now because of a rename of --max-size to --max_size

RUN apt-get update \
	&& apt-get install -y wget libxml-libxml-perl

RUN wget http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.0/sratoolkit.2.10.0-ubuntu64.tar.gz -O /tmp/sratoolkit.tar.gz \
	&& tar zxvf /tmp/sratoolkit.tar.gz -C /opt/ && rm /tmp/sratoolkit.tar.gz

ENV PATH="/opt/sratoolkit.2.10.0-ubuntu64/bin/:${PATH}"

# Updating is required before any apt-gets
RUN pip install geofetch
