# Dockerfile for graphics environment (visualization software):

FROM nsheff/texextra

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

RUN apt-get update
RUN apt-get install inkscape -y
RUN apt-get install -y imagemagick
RUN apt-get install -y librsvg2-bin
RUN apt-get update --fix-missing
RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula \
    select true | debconf-set-selections && \
    apt-get install -y ttf-mscorefonts-installer
RUN fc-cache -f -v
RUN apt-get install -y libcanberra-gtk-module
