FROM ubuntu:18.04

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

# Updating is required before any apt-gets
RUN apt-get update && apt-get install -y wget git
RUN apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip
RUN apt-get install -y python3-venv

# I added these in for pysam. Maybe would be nice to use the host installs? Couldn't figure that out easily. Or stick them upstream.
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libbz2-dev
RUN apt-get install -y liblzma-dev

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN pip install ipython


CMD ["python3"]
