FROM ubuntu:18.04

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

# Updating is required before any apt-gets
RUN apt-get update && apt-get install -y wget git
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make python-sphinx
RUN apt-get install -y python-pip python-dev build-essential
RUN pip install sphinx_rtd_theme
RUN pip install pyyaml psutil
# RUN apt-get install -y python3 
