FROM ubuntu:18.04
MAINTAINER Nathan Sheffield <nathan@code.databio.org>
RUN apt-get update
RUN apt-get install -y software-properties-common && apt-add-repository ppa:git-core/ppa
RUN apt-get update && apt-get install -y git
