# Dockerfile for sublime
FROM ubuntu:18.04

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

ENV NO_AT_BRIDGE=1
ARG DEBIAN_FRONTEND=noninteractive


RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install \
    	locales \
        libgtk-3-0 \
        dbus-x11 \
        curl
ARG SUBLIME_BUILD="${SUBLIME_BUILD:-3207}"

RUN locale-gen en_US.UTF-8

RUN curl -O https://download.sublimetext.com/sublime-text_build-"${SUBLIME_BUILD}"_amd64.deb && \
	dpkg -i sublime-text_build-"${SUBLIME_BUILD}"_amd64.deb || echo "\n Will force install of missing ST3 dependencies...\n"


ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8

